name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      run: git clone https://github.com/mykhalska/test-repo .
    name: Continuous Integration

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12' # Change this to your desired Python version
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt 
        
    - name: Run unit tests
      run: echo 'Tests to be added'
    
